miraclx/freyr-js

src/walkr.js

When walking an object tree, with multiple lookup keys, ignore the rest when one lookup fails.
``` js
walkr({a: {b: {c: 10}}}, 'a', 'd', 'b');
```
Naturally, this should lookup `a` in the source object, `d` in the result from the lookup of `a` and thereafter `b` in the result from the lookup of `d`. But the `d` lookup fails and should promptly break lookups and return.
Currently, `b` is being queried from a `null` object returned from the failed `d` lookup. That's just wrong.
Fixes #17.

walkr: properly handle early lookup failures at consecutive walks

---

package.json

NPM dependency [`@yujinakayama/apple-music-node`](https://github.com/yujinakayama/apple-music-node) [`v0.4.0`](https://www.npmjs.com/package/@yujinakayama/apple-music/v/0.4.0) @ [efea39c](https://github.com/yujinakayama/apple-music-node/commit/efea39c44db8ccbe45068f6cd2bfeacc4137588c), hasn't addressed critical security vulnerability in its dependency `axios`.
Until this happens, we'd switch to autogenerated dependabot branch that does fix this https://github.com/yujinakayama/apple-music-node/pull/4.

npm: workaround dependency master, fix security vuln

---

package.json

NPM dependency [`youtube-dl`](https://github.com/przemyslawpluta/node-youtube-dl) [`v3.1.0`](https://www.npmjs.com/package/youtube-dl/v/3.1.0) @ [1b4e5a6](https://github.com/przemyslawpluta/node-youtube-dl/commit/1b4e5a65447fcdbe7c7030925359cb045b5199a4), hasn't addressed deprecation and potential migration from `request` https://github.com/request/request/issues/3142.
As a workaround, we incorporate the unmerged PR that does addresses this https://github.com/przemyslawpluta/node-youtube-dl/pull/299 with [BarryCarlyon/node-youtube-dl](https://github.com/BarryCarlyon/node-youtube-dl/tree/replacerequest) @ [`replacerequest`](https://github.com/BarryCarlyon/node-youtube-dl/tree/replacerequest) and the fairly active HEAD of the origin repo into a fork of both for synchronizing commits …

npm: workaround request deprecation message with personal fork

---

src/services/youtube.js

|  meta | value |
| ---- | ----- |
| `title` | `"Supalonely"` |
| `artist[0]` | `"BENEE"` |
| `artist[1]` | `"Gus Dapperton"` |
| ref | title | artist[0] | artist[1] | album | explicit | link |
| --- | ----- | --------- | --------- | ----- | -------- | ---- |
| `0` | `"Supalonely (feat. Gus Dapperton)"` | `"BENEE"` | | `"STELLA & STEVE"` | `false` | [link](https://music.youtube.com/watch?v=SztvQd1eYlI&feature=share) |
| `1` | `"Supalonely (feat. Gus Dapperton)"` | `"BENEE"` | | `"STELLA & STEVE"` | `true` | [link](https://music.youtube.com/watch?v=bMQN-uJa2Ac&feature=share) |
| `2` | `"Supalonely (feat. Gus Dapperton)"` | `"BENEE"` | | `"Hey u x"` | `true` | [link](https://music.youtube.com/watch?v=o47dgV2xMcQ&feature=share) |
In the result, `artist[1]` from `Query` is inside the title. …

YouTubeMusic: include artists(s) in stripped filter

---

docker/Dockerfile.alpine
docker/Dockerfile.archlinux

Incorrect behavior spotted in #47 
```console
docker run -it --rm freyrcli/freyrjs urify https://open.spotify.com/playlist/37i9dQZF1DWWEcRhUVtL8n
```
should run the `urify` subcommand instead of wrongly attempting to download from a URI called `urify`

docker: set entrypoint to `freyr` command instead of `freyr get`

---

README.md
cli.js
package-lock.json
package.json
src/services/youtube.js

Fixes #78.
- Drops deprecated https://github.com/przemyslawpluta/node-youtube-dl dependency
- Defers to https://github.com/microlinkhq/youtube-dl-exec

drop deprecated dep; update youtube-dl

---

src/services/youtube.js

fix: workaround for feeds whose id's start with hyphen

---

src/services/apple_music.js

Fixes #74
Not all `releaseDate`-s from the server response is fully qualified as in `2017-09-24`.
Some, are just years instead, like `2017`

fix edge case where server doesn't return a fully qualified date

---

cli.js

Sometimes, `freyr` gets stuck after displaying stats. There seems to be some async tasks still processing in the background. We need to investigate this. In the meantime, this patch forces the process to exit after waiting 1 second, assuming clean exit.

fix: force exit if hung

---

renovate.json
renovate.json5

Skip updating the following:
- GitHub Actions
- `docker/login-action` (https://github.com/miraclx/freyr-js/pull/133)
- `docker/metadata-action` (https://github.com/miraclx/freyr-js/pull/134)
- `docker/build-push-action` (https://github.com/miraclx/freyr-js/pull/132)
- NPM
- `got` (https://github.com/miraclx/freyr-js/pull/116)
- `filenamify` (https://github.com/miraclx/freyr-js/pull/115)

chore(renovate): skip updating docker action images, got, filenamify

---

.github/workflows/test.yml

Run CI tests on Wednesday and Saturdays, weekly. Helps make sure we catch any issues before users report them.

feat(CI): schedule CI testing twice weekly

---

package-lock.json
package.json

[`yt-search`](https://github.com/talmobi/yt-search) needs to update its dependency on [`node-fzf`](https://github.com/talmobi/node-fzf) which also needs to update its dependency on [`string-width`](https://github.com/sindresorhus/string-width).
Full NPM audit report:
```console
$ npm audit
ansi-regex  >2.1.1 <5.0.1
Severity: moderate
Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix --force`
Will install yt-search@0.1.1, which is a breaking change
node_modules/strip-ansi/node_modules/ansi-regex
strip-ansi  4.0.0 - 5.2.0
Depends on vulnerable versions of ansi-regex
node_modules/strip-ansi
string-width  2.1.0 - 4.1.0
Depends on vulnerable versions of strip-ansi
node_modules/string-width
node-fzf …
```

fix(vulnerability): override versions of node-fzf and string-width

---

package-lock.json
package.json
src/services/apple_music.js

[`@yujinakayama/apple-music-node`](https://github.com/yujinakayama/apple-music-node) got updated to [`v0.4.1` on NPM](https://www.npmjs.com/package/@yujinakayama/apple-music/v/0.4.1) a couple of days back, we can now drop the temporary patch.
https://github.com/yujinakayama/apple-music-node/issues/5

chore: revert to upstream dep for apple-music

---

cli.js

Some package managers provide the AtomicParsley all lowercased.. (as `atomicparsley`)
This enables compatibility for either case.
Fixes: https://github.com/miraclx/freyr-js/issues/67

feat: AtomicParsley / atomicparsley

---

README.md

freyr uses YouTube Music / YouTube to source raw audio. This updates the documentation to be more explicit about it.
Resolves: #130 #101

chore(doc): improve docs to be explicit about sourcing from YouTube

---

package-lock.json
package.json

- `yt-search` depended on `node-fzf` which depended on a stale version of `cli-color` depending on a vulnerable version of `ansi-regex`
- `libxget` and `@yujinakayama/apple-music` both depended on the now stale `axios@0.21.4` which depended on a vulnerable version of `follow-redirects`

fix(vuln): update and override deps versions to fix vulnerability

---

package-lock.json

`cli-color v2` dumped `ansi-regex v2` for security vulnerabilities https://github.com/medikoo/cli-color/pull/38

chore: dump ansi-regex v2

---

CHANGELOG.md
package-lock.json
package.json

Scheduled release: 21-02-2022
Notable changes:
- All dependencies updated.
- Support `"single"` specification in `"type"` filter. https://github.com/miraclx/freyr-js/pull/124
- Address hanging problem on exit. https://github.com/miraclx/freyr-js/pull/125
- Touch up final stats. https://github.com/miraclx/freyr-js/pull/126
- Fix `AND` and `OR` behavior when dealing with filters. https://github.com/miraclx/freyr-js/pull/127
- Added the `CHANGELOG.md` file to track project changes. https://github.com/miraclx/freyr-js/pull/148
- Introduced CI runtime checks. https://github.com/miraclx/freyr-js/pull/121
- Introduced CI lint checks. https://github.com/miraclx/freyr-js/pull/123 https://github.com/miraclx/freyr-js/pull/137
- Automated the CI release process. …

chore: version to 0.6.0

---

Dockerfile

https://github.com/miraclx/freyr-js/issues/164 highlighted an issue with the docker image. This fixes that by ensuring an intermediate installation step, bundling the dependencies in the docker image.

fix: bundle dependencies with docker image

---

CHANGELOG.md
README.md
package-lock.json
package.json

Scheduled release: 09-06-2022
Notable changes:
- Updated Apple Music access key. <https://github.com/miraclx/freyr-js/pull/191>
- Simplified the output of using the `-v, --version`. <https://github.com/miraclx/freyr-js/pull/152>
- Dropped extra version in the header. <https://github.com/miraclx/freyr-js/pull/153>
- Fixed issue with docker build not bundling dependencies. <https://github.com/miraclx/freyr-js/pull/165>
- Update dependencies.

chore: version to 0.7.0

---

Dockerfile

Fixes #194
__**CHANGELOG:**__
Edited the atomicparsley installation step in the Dockerfile.
Insead of downloading the precompiled binary, now clones the repo at the latest stable tag and compiles it at image build time.
This fixes the issue of AtomicParsley only working on x86 images, because it gets build for the target architecture like the image.

Failed while embedding metadata [255]

---

.github/workflows/tests.yml

Since https://github.com/miraclx/freyr-js/pull/214, we now build and push docker images from each PR.
This allows for visibility on the progress and exposes the image tag.

chore(CI): report docker image build progress

---

src/stack_logger.js

Before now, freyr autodetects if its output was being piped, and forces write to a tty instead of the pipe.
This reverts that behaviour. By default, we now print to stdout.
Only the progressbar is forced to a tty and is exempt from the stream.

chore: drop persistent printing behaviour, default to stdout

---

README.md

Since https://github.com/miraclx/freyr-js/pull/218, every submitted PR gets an associated docker image tag.
This documents the process in the readme.

chore: document docker autobuild

---

.github/workflows/tests.yml

Adds a size comparison between the docker image generated from the PR patch in comparison to the latest master.
Before:
> ![image](https://user-images.githubusercontent.com/16881812/177126499-c4a855e1-fc3d-4f87-a943-e7b05f95a1d2.png)
After:
> ![image](https://user-images.githubusercontent.com/16881812/177126380-afaa40bf-8d34-4a8a-9e80-cad96e5dacfb.png)

chore(CI): add badges to PR docker build comments

---

.github/workflows/tests.yml

Part 1 of #238, docker images built from every push to master should stay referentiable.
This would ensure that a commit would always have an associated docker image.

chore: docker images for master commits stay persistent

---

Dockerfile

Alpine installing `python3` isn't sufficient enough for `youtube-dl` that seeks the presence of the `python` command.
Instead of installing another `python` binary, we link it.

chore(CI): link python to python3

---

.eslintrc
package-lock.json
package.json
yarn.lock

We dropped the need for babel quite a while ago.

deps: remove @babel/eslint-parser

---

Dockerfile

Use `yarn install --prod --frozen-lockfile` instead of `npm ci --omit=dev`.
Local testing shows it produces lighter sized `node_modules`.

chore(CI): use yarn install in Dockerfile

---

Dockerfile

The `__pycache__` folder contains a bunch of precompiled binaries typically used to optimize runtime for python libraries.
But really, they don't need to come bundled with our final image. We can have them compiled just in time.

chore: remove __pycache__ stripping heavy binaries in our final image

---

Dockerfile

Remove any python wheels in the image.
Notably `/usr/lib/python*/ensurepip/_bundled/*.whl`
Contributes to making the docker image lighter: #257

chore: remove python wheels

---

.dockerignore
Dockerfile

Try as much as possible to let undepending steps build independently of each other.
Helps take maximum advantage of the build cache.
And apparently final image size, so this contributes to https://github.com/miraclx/freyr-js/issues/257

docker: resolve interdependencies

---

Dockerfile
freyr.sh

Sometimes, when running freyr inside its docker container, it won't receive signals. But running it via a shell would appropriately send those signals to the freyr process.

docker: run freyr inside shell to allow proper signalling

---

test/index.js

CI would get stuck whenever a service fails to authenticate as freyr would fallback to the authentication procedure. Which would require action from the user. Since the user can't provide any input while in CI, freyr should just fail outright.
https://github.com/miraclx/freyr-js/actions/runs/2664123334

chore: skip service authentication when running in CI

---

test/index.js

Adds a line that shows the command executed for each test unit
```
> freyr@0.7.0 test
> node test/index.js
Log File: /tmp/freyr-test/b8b81f50-1957-4c05-b6e5-e06b6477355c/spotify-track-1.log
┌──> [1/3] spotify track ────────────────────────────────────┐
│ 
│ $ docker run --rm --interactive --log-driver=none --name b8b81f50-1957-4c05-b6e5-e06b6477355c freyr-dev:master --no-logo --no-header --no-bar https://open.spotify.com/track/5FNS5Vj69AhRGJWjhrAd01
│ 
│ Checking directory permissions...[done] 
```

test: print command line when executing test units

---

test/index.js

When running freyr inside a docker image, and it fails to authenticate, it requires input from the user. This allows us to bind a port inside the container with one on the host so you can open the local url in your browser to complete the authentication procedure.

allow authentication through a docker image

---

.eslintrc

https://github.com/miraclx/freyr-js/runs/7665631006?check_suite_focus=true
https://github.com/github/super-linter/issues/2871

eslint: ignore cli_server because of super linter

---

test/index.js

`npm test -- --force` should allow reusing existing stages not recreating existing tracks in retried runs

ci: fix the behaviour of the `--force` arg

---

Dockerfile
freyr.sh

When running freyr from inside docker desktop, add the `DOCKER_DESKTOP=true` environment variable.
That tells freyr to fall into shell mode.
Once in shell mode, you can run the `freyr` command directly.
Fixes #313.

add shell pause when run from docker desktop

---

.github/workflows/tests.yml
cli.js
package-lock.json
package.json
src/file_mgr.js
src/symbols.js
test/index.js
yarn.lock

This one is a mix of a couple of improvements
- the use of `.code` for status reporting was very ambiguous, and hid a couple of errors behind "unknown error", when the error is in fact known.
- Fixes the bug in #305
<details>
<summary> (click to view) </summary>
```console
│   • [✓] 01 make believe
│ /freyr/node_modules/@ffmpeg/core/dist/ffmpeg-core.js:12
│ if(h){pa=la?require("path").dirname(pa)+"/":__dirname+"/";ra=function(a,b){ta||(ta=require("fs"));va||(va=require("path"));a=va.normalize(a);return ta.readFileSync(a,b?null:"utf8")};sa=function(a){a=ra(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ha=process.argv[1].replace(/\\/g,"/"));fa=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof wa))throw …
```

fix some errors

---

cli.js
src/file_mgr.js
src/symbols.js
test/index.js

Could be the case that a playlist, or an artist with two identical albums have identical tracks. Freyr, resolving them to the same source, ends up downloading the track to the same cache stage, encoding and writing it out to the same output file.
Lots of potential for clashes, and race conditions. At the end of the day, the file may end up corrupt.
It's a game of russian roulette, basically.
This patch makes it so, a file is only ever touched by freyr once in the entire lifetime of the program's execution.
So if a track is being downloaded by being on another album, that download task carries through for the whole program.
And if they're writing to the same file, well, only one gets to do the writing.

Mutual exclusion for file writes

---

freyr.sh

hide stty error message when docker is run without an attached tty

---

.github/workflows/tests.yml
src/services/apple_music.js

Fixes #177.
Test Cases:
- From the original issue: https://music.apple.com/us/playlist/music3/pl.u-55D6X83H8lWGzjB
- And this 331-track playlist: https://music.apple.com/us/playlist/this-is-the-longest-playlist-ever/pl.u-d2b05b2uMv8Algy

Apple Music: Add Pagination

---

CHANGELOG.md
README.md
cli.js
conf.json

Closes #258.
This introduces the `-D, --check-dir` flag and moves the older `-D, --downloader` flag to a more appropriate name `-S, --sources`
This lets us only download tracks if they don't exist in the base directory, as well as a list of other directories.
Syntax:
- Repeatable: `-D dir1 -D dir2`
- Comma-separated: `-D dir1,dir2`
1. Track doesn't exist in the output directory, but does in any of the check directories
```console
$ freyr https://open.spotify.com/track/6AwhhAhVLPvaDYmfR4j3bQ -d music -D a,b,c
...
• [03 Bonafide (feat. Chiiild)]
| [»] Track exists. Skipping...
| [»] Found In:
| [»]  - a/Emotional Oranges/The Juicebox/03 Bonafide (feat. Chiiild).m4a
| [»]  - b/Emotional Oranges/The Juicebox/03 Bonafide (feat. Chiiild).m4a
| [»]  - c/Emotional Oranges/The Juicebox/03 Bonafide …
```

layered base dir

---

cli.js

Fixes https://github.com/miraclx/freyr-js/issues/356

Removed unimplemented commands and arguments

---

cli.js
src/async_queue.js

As it should be, but also because, as observed in #370, `ffmpeg-wasm` now requires an explicit call to `ffmpeg.exit` which we can only do after freyr is done with it.

cleanup any provisioned resources

---

cli.js

Allows you pipe in a list of URIs/URLs and get out a valid freyr input file.
```console
$ cat links | freyr urify --no-header --no-logo > ./download_queue
$ freyr -i ./download_queue
```

fix(urify): print misc logs to stderr

---

freyr.sh
test/index.js

Since the docker image is launched with `--network host`, we can also forward arguments defined in `NODE_ARGS`.
Part of https://github.com/miraclx/freyr-js/pull/372.
Let's us do:
```console
$ NODE_ARGS="--inspect" yarn test spotify.track --docker freyrcli/freyrjs-git:master
```

allow NODE_ARGS input when using a Docker image for testing

---

cli.js
src/services/apple_music.js

Fixes https://github.com/miraclx/freyr-js/issues/395. Introduces artist albums pagination.
Part of #348.

feat(Apple Music): introduce artist albums pagination

---

CHANGELOG.md
src/services/apple_music.js
src/services/deezer.js
test/default.json

Apple Music: Support album urls that don't include the album name. ex. `https://music.apple.com/de/album/1581087024?l=en` As in #402.
Deezer: Restrict ID validity to numbers only. As it should've been.
Fixes #402.

chore: fix regexes

---

conf.json

Fixes https://github.com/miraclx/freyr-js/issues/443, updates the Apple Music access token.

chore: update apple music access token

---

Dockerfile
cli.js
conf.json
package-lock.json
package.json
yarn.lock

Fixes https://github.com/miraclx/freyr-js/issues/436.
Updates youtube-dl-exec, which subsequently downloads the latest version of yt-dlp.
Notable changes:
- https://github.com/yt-dlp/yt-dlp/pull/3044 replaced `path` in the feeds to `url`.

chore: update youtube-dl-exec

---

cli.js
package-lock.json
package.json

https://github.com/miraclx/freyr-js/pull/455 modified the field names for Spotify credentials to camelCase as opposed to snake_case.
This patch makes it possible to migrate old versions of the config on existing users devices.
Fixes this (reported in https://github.com/miraclx/freyr-js/issues/466#issuecomment-1494451868)
```console
[!] Fatal Error: Config schema violation: `services/spotify` must NOT have additional properties; `services/spotify` must NOT have additional properties
```

chore: add config migrations

---

src/services/apple_music.js

Implemented Track Artist Pagination
Fixes #419, originally mentioned in https://github.com/miraclx/freyr-js/issues/395.
Part of https://github.com/miraclx/freyr-js/pull/348
Test track: `apple_music:track:1208190370`

feat(Apple Music): impl track artists pagination

---

cli.js
src/services/youtube.js

In cases like `apple_music:track:1208190370` where there's only one word in the track name, with all artists squashed into one entry, the odds of weighing the correct track is 50%, which is far under the cut-off of 70%
This patch rewrites that logic to stop presupposing either the track has more than one word, or there's more than one artist.
Now, we're embedding the album as well in there, taking the minimum odds of success to 66%, but we undercut by just a bit at 65%.
Issue originally derived from https://github.com/miraclx/freyr-js/issues/395#issuecomment-1385146417.

chore: revisit YouTube Music track weighing logic

---

src/text_utils.js

In cases like `apple_music:track:1208190370` where the track name is "Solidarité", `StripChar.RSspecChar` treats the accented `é` as a non-alphanumeric character and strips it. Leaving "Solidarit" which leads to incorrect results.
This patch normalizes those inputs, which in the case of "Solidarité`, results in "Solidarite".
Issue originally derived from https://github.com/miraclx/freyr-js/issues/395#issuecomment-1385146417, #419.

fix(text-utils): normalize accented words

---

cli.js

Binaries in the `bin/{posix,windows}` folder take precedence over the ones in the `PATH`.

feat: local bins override globals

---

Dockerfile
README.md

Update `AtomicParsley`, following https://github.com/wez/atomicparsley/pull/63.
Revert to upstream when that patch is merged, and a new release is cut.

chore: update AtomicParsley in Docker, update docs

---

src/services/youtube.js

Related upstream issue: https://github.com/microlinkhq/youtube-dl-exec/issues/153
Our dependency youtube-dl-exec treats non-empty stderr content as hard errors. And since yt-dlp also writes warnings to stderr, youtube-dl-exec fails to handle those cases where a warning isn't an error.
This patch makes it so yt-dlp doesn't emit any warnings.

fix(YouTube): ignore errors when we call out to yt-dlp

---

cli.js

Looks like `yt-dlp` might've changed the output format expected by freyr. In previous versions, `abr` and `vbr` in the json data used to be `null` when not specified. Now, it's `0` when not specified.
This updates the logic to adapt to that.

chore: fix source feed extraction

---

.github/workflows/tests.yml

Context: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
`echo "::set-output name={name}::{value}"`
was fazed out in favor of
`echo "{name}={value}" >> $GITHUB_OUTPUT`

chore(CI): update step output format

---

cli.js

Fresh runs of freyr shouldn't be getting the message "Migrating config file to v0.9.1"
This also dumps all spotify related config pre-v0.9.1 since https://github.com/miraclx/freyr-js/pull/454 introduced new credentials. There's no point in retaining old tokens.

chore: cleanup migration logic

---

cli.js
conf.json

`freyr <src> -d ..` will check the current working directory for the presence of the track which isn't the behaviour we intend to have.
This patch fixes that.

fix: cwd should not be implicitly checked when the download dir is elsewhere

---

README.md
cli.js
src/services/apple_music.js
src/services/deezer.js

Before this patch, the `urify` command didn't work as expected with Apple Music and Deezer.
Outright broken with Apple Music parsing, with the error:
```console
TypeError: Cannot read private member #store from an object whose class did not declare it
at Object.parseURI (file:///freyr-js/src/services/apple_music.js:103:50)
at FreyrCore.parseURI (file:///freyr-js/src/freyr.js:43:39)
```
And failing to return URLs when requested (`--url`) for Deezer.
Working on this patch, I also realized Apple Music URLs need to be qualified with the album IDs.
So, with a URL of https://music.apple.com/us/album/say-so-feat-nicki-minaj/1510821672?i=1510821685
The previous URIfication would result in `apple_music:track:1510821685`
And attempting to reconstruct a URL from that would be missing the album ID - …

fix: urify logic for Apple Music and Deezer

---

CHANGELOG.md
README.md
cli.js
conf.json
package-lock.json
package.json
yarn.lock

Scheduled release: 08-08-2023
Notable changes:
- Changed Spotify credentials, introduced migrations to mitigate any complications. <https://github.com/miraclx/freyr-js/pull/454>, <https://github.com/miraclx/freyr-js/pull/470>, <https://github.com/miraclx/freyr-js/pull/526>
- Improved the YouTube Music track weighing logic, we should get 30% more accurate results. <https://github.com/miraclx/freyr-js/pull/472>
- Freyr now supports paginated track artists. <https://github.com/miraclx/freyr-js/pull/471>
- Accented words like `Solidarité` now get properly normalized, helping more accurate lookups. <https://github.com/miraclx/freyr-js/pull/473>
- Fix bug with Apple Music & Deezer URI parser. <https://github.com/miraclx/freyr-js/pull/403>, <https://github.com/miraclx/freyr-js/pull/549>
- Freyr …

chore: version to 0.10.0

---

README.md
cli.js
src/services/apple_music.js
test/urify.js

Continued patch for https://github.com/miraclx/freyr-js/pull/549
Turns out Apple Music supports this URL format: `https://music.apple.com/us/song/1699712652`
Instead of the more verbose: `https://music.apple.com/us/album/delresto-echoes-feat-beyonc%C3%A9/1699712635?i=1699712652`
This removes the need for the newly introduced extended URI format for Apple Music.
So we can revert back to `apple_music:track:1699712652` from `apple_music:track:1699712635i1699712652`
Props to @LeBradshaw for bringing this to my attention in #541.

feat(Apple Music): add support for song-type URLs

---

src/services/apple_music.js
src/services/spotify.js

JS objects have no guarantees of maintaining insertion order. The use of `fromEntries` to construct an object of numeric keys orders them numerically. Which is not what we want.
Fixes #568.
This is observable in the case of Apple Music, but even though we use the same logic for Spotify, their IDs are alphanumeric, so insertion order appears to be preserved. But we rewrite that section of code as well for correctness.

fix: collection order

---

package-lock.json
package.json
src/text_utils.js
yarn.lock

We previously used the library `stripchar` to remove symbols from the query sent off to YouTube( Music).
The logic in there was using the regex `[^a-zA-Z 0-9]` which removed all non-alphanumerics including non-Latin letters.
This isn't the behaviour we want. We want non-Latin letters to work as well.
So this patch defers to unicode categorizations and hand writes the replacement logic.

fix: support multi-lang source feed lookup

---

src/services/apple_music.js

Following the reversal of the Apple Music track URI update from https://github.com/miraclx/freyr-js/pull/549 in https://github.com/miraclx/freyr-js/pull/552.
The update of the urified format was not reverted.
This patch fixes that.

fix(Apple Music): fix incorrect Apple Music uri report

---

cli.js

For tracks we've determined to skip for whatever reason (existence or filter mismatch) - ensure to avoid acquiring source information.

fix: avoid requesting source data for skipped tracks

---

src/services/youtube.js

YouTube Music seems to have removed the "Song" label on songs in its search results. Requiring us to update our extraction logic.
While at this, I updated the accuracy gauge to factor in the weight of texual labels as well.
All together, cutting off at a minimum of 80% match.

fix(YouTube Music): fix song extraction

---

cli.js

In cases that don't require loadConfig to be authenticated, like Deezer. We'd get two reports of '[authenticated]`.

fix: dedupe authenticated report

---

cli.js

Apple Music would use `℗ {YEAR} {LABEL}` where Spotify would use `(P) {YEAR} {LABEL}`
This standardizes it to prefer Apple Music's

feat: standardize copyright format

---

README.md
cli.js
src/services/apple_music.js
src/services/spotify.js

Deezer's API unfortunately, doesn't include any way to derive the total disc count of an album.
There's an alt-API we could use for this (which also provides us copyright information)
```console
$ xh 'https://www.deezer.com/ajax/gw-light.php?method=deezer.getUserData&api_version=1.0&api_token=' \
| jq '{cf: .results.checkForm, sid: .results.SESSION_ID}'
{
"cf": "8MBdPkLVd3V~Exj0gJP0chXXXgM~2yb0",
"sid": "fr0f7920da51b1f2b72dbbc7052a4a4141872d94"
}
$ xh 'https://www.deezer.com/ajax/gw-light.php?method=deezer.pageAlbum&api_version=1.0&api_token=8MBdPkLVd3V~Exj0gJP0chXXXgM~2yb0' \
cookie:sid=fr0f7920da51b1f2b72dbbc7052a4a4141872d94 \
alb_id:=264169542 lang=us \
| jq -r '{total_discs: [.results.SONGS.data[] | .DISK_NUMBER] | unique | sort | reverse[0], copyright: .results.DATA.PRODUCER_LINE}' …
```

fix(meta): use correct total disc number count

---

README.md
src/services/deezer.js

https://github.com/miraclx/freyr-js/pull/634/#issue-2080542052 highlighted an alternative API for Deezer that provides copyright information as well as disk numbers for all tracks in the album.
The implementation in this PR makes Deezer feature complete.
> There's an alt-API we could use for this (which also provides us copyright information)
> 
> ```console
> $ xh 'https://www.deezer.com/ajax/gw-light.php?method=deezer.getUserData&api_version=1.0&api_token=' \
>   | jq '{cf: .results.checkForm, sid: .results.SESSION_ID}'
> {
>   "cf": "8MBdPkLVd3V~Exj0gJP0chXXXgM~2yb0",
>   "sid": "fr0f7920da51b1f2b72dbbc7052a4a4141872d94"
> }
> 
> $ xh 'https://www.deezer.com/ajax/gw-light.php?method=deezer.pageAlbum&api_version=1.0&api_token=8MBdPkLVd3V~Exj0gJP0chXXXgM~2yb0' \
> …
```

feat(Deezer): workaround for fetching copyright & total disk number

---

Dockerfile

Add a test to ensure the `yt-dlp` binary is present after `install` has been run.
> Found out why CI was failing, over-dependence on caches. Looks like 2 months ago, we cached an image that didn't appropriately download the `yt-dlp` subdependency of `youtube-dl-exec` and we kept reusing that image since freyr didn't change in this period of time.
> 
> Had to evict caches, and now it works! - [miraclx/freyr-js/actions/runs/8623905754/job/23690297872](https://github.com/miraclx/freyr-js/actions/runs/8623905754/job/23690297872)
_Originally posted by @miraclx in https://github.com/miraclx/freyr-js/issues/669#issuecomment-2048877760_
Linked: https://github.com/microlinkhq/youtube-dl-exec/issues/190

chore: assert the presence of the yt-dlp dep
