- src/services/youtube.js
Added a walk() function to find the first property in an object
graph.
And then updated tags, removing the join() and flattening into
a single list, which fixed the splice() and array index operations.
Fixes #2.
> Fix youtube search.

- package.json
- src/services/youtube.js
> Fix YouTube Search

- src/services/spotify.js
> Spotify: add support for batching for playlists.

- conf.json
> Apple Music: Update developerToken

- src/services/youtube.js
- src/walkr.js
> Rewrite YouTube Music Search Parsing

- cli.js
> cli: fix local bin PATH resolution

- .gitignore
- package-lock.json
As mentioned here https://github.com/miraclx/freyr-js/issues/44#issuecomment-789316621
We include a lockfile to ensure dependency consistency
> add npm lockfile

- cli.js
- src/services/apple_music.js
> fix storefront handling

- conf.json
- src/services/apple_music.js
Fixes #70, Update AppleMusic Access Key, and update release date source after the update from the server response!
> Update AppleMusic Access Key

- conf.json
Fixes #91, updates AppleMusic access key
> chore: update apple music api key

- README.md
- cli.js
<table>
<thead>
<tr>
<th> ♾️ </th>
<th>Before</th>
<th></th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
<pre code="text">
========== Stats ==========
[•] Total tracks: [25]
» Skipped: [15]
✓ Passed:  [08]
✕ Failed:  [02]
===========================
</pre>
</td>
<td rowspan=4> ➡️ </td>
<td>
<pre code="text">
============ Stats ============
[•] Total tracks: [25]
» Skipped: [10]
✓ Passed:  [13] (new: 08)
✕ Failed:  [02]
===============================
</pre>
</td>
</tr>
<tr>
<td>
<code> Skipped </code>
</td>
<td>
previously existed + filtered out
</td>
<td>
filtered out
</td>
</tr>
<tr>
<td>
<code> Passed </code>
</td>
<td>
newly dowloaded
</td>
<td>
previously existed + newly downloaded
</td>
</tr>
<tr>
<td>
<code> Failed </code>
</td>
<td>
failed tracks
</td>
<td>
failed …
> feat: revise final stats, use hint for new songs

- cli.js
Guarantee this behaviour;
`--filter a,b --filter c,d`: `(a AND b) OR (c AND d)`
> fix: filter validator

- .github/workflows/ci-prep.sh
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
With this pipeline, we ensure to test the following on every PR:
And introduce automated publishing on tags:
> feat: introduce CI testing

- package-lock.json
Update `libxget-js` from `v0.9.0` to `v0.9.1` https://github.com/miraclx/libxget-js/pull/7
> chore(deps): update libxget-js depenency

- .github/workflows/publish.yml
- CHANGELOG.md
> feat(CI): add workflow for automating releases to GitHub

- cli.js
Fixes #151, prints just the version when requested.
> chore: `simplify -v, --version`

- cli.js
```diff
____                    
/ __/_______  __  _______
/ /_/ ___/ _ \/ / / / ___/
/ __/ /  /  __/ /_/ / /    
/_/ /_/   \___/\__, /_/     
/____/ v0.6.0
- freyr v0.6.0 - (c) Miraculous Owonubi <omiraculous@gmail.com>
- -------------------------------------------------------------
+ freyr - (c) Miraculous Owonubi <omiraculous@gmail.com>
+ ------------------------------------------------------
```
> chore: drop extra version in header

- conf.json
- src/services/apple_music.js
Fixes #91, updates AppleMusic access key
> chore: update apple music access key

- src/services/youtube.js
Got `v12.0.0` dropped implicit timeout - https://github.com/sindresorhus/got/releases/tag/v12.0.0.
> chore: fix got timeout handling

- package-lock.json
- package.json
- yarn.lock
`axios` and `tough-cookie` are unused.
> chore: drop unused deps

- .github/workflows/tests.yml
- renovate.json
> chore(CI): add docker image reporting to PRs

- .github/workflows/tests.yml
> chore(CI): update docker image twice per run only

- .github/workflows/tests.yml
Along with #239, this resolves #238.
> chore(CI): reference origin sha

- .github/workflows/tests.yml
Ensure yarn.lock stays up to date.
> chore(CI): ensure yarn.lock stays up to date

- .github/workflows/tests.yml
Since the image behind "last master" updates everytime master is merged into, it reflect the latest master prior to the the PR merging.
> Last Master is actually Latest Master

- Dockerfile
Remove:
- freyr media assets
- `.map` files inside `node_modules`
> docker: prune more unnecessary assets

- Dockerfile
> docker: pin docker base images

- .github/workflows/ci-prep.sh
- CHANGELOG.md
- cli.js
Added the `--no-bar` flag that toggles the visibility of the progress bar.
> chore: make it possible to disable the progressbar

- .github/workflows/tests.yml
> chore(CI): reorder split services

- .github/workflows/publish.yml
- .github/workflows/tests.yml
Experiment with docker build caching to see if it translates into faster build times.
> chore(CI): cache docker artifacts

- .github/workflows/tests.yml
This helps us test both freyr and the docker image built from it.
> chore: test freyr through a docker container

- cli.js
dns check somehow fails for me over VPN, https check always works
> use https check instead of dns check for network connection

- src/cli_server.js
- added font
- made the box more vertically centered
- font color
- eased the shadows
- changed the box color to a neat gradient
- adjusted viewport to look better on smaller screens
| Before (Desktop) | After (Desktop) |
| - | - |
| ![Screenshot_20220804_080914](https://user-images.githubusercontent.com/16881812/182761129-a74178a9-22cb-4299-960e-284f251bc681.png) | ![Screenshot_20220804_080939](https://user-images.githubusercontent.com/16881812/182761155-1ae020b8-ae78-475c-9b19-270b405d9a8c.png) |
| Before (Mobile) | After (Mobile) |
| - | - |
| ![Screenshot_20220804_080659](https://user-images.githubusercontent.com/16881812/182760864-aafab669-1167-4f99-b5ab-b4cb4c9fbe4f.png) | ![Screenshot_20220804_080719](https://user-images.githubusercontent.com/16881812/182760889-5e9c7072-fe1a-4071-88 …
> touchup the auth page a bit

- .github/linters/.eslintrc
- .github/workflows/tests.yml
- src/services/apple_music.js
```
freyr - (c) Miraculous Owonubi <omiraculous@gmail.com>
------------------------------------------------------
Checking directory permissions...[done] 
[!] Failed to initialize a Freyr Instance
this[#store].core.albums.axiosInstance.create is not a function
```
credit to @dmisdm from #242
> patch axios create error

- Dockerfile
- cli.js
- package-lock.json
- package.json
- yarn.lock
A dependency of ours published a minor release with some breaking changes.
Fixes #162
> fix youtube source lookup logic

- .github/workflows/tests.yml
Add compare button to PR docker image report. Comparison via slim.ai.
> ci: add compare button

- .github/workflows/tests.yml
- TEST.md
- cli.js
- src/file_mgr.js
- test/index.js
> revamp test infra

- cli.js
- src/file_mgr.js
- test/index.js
Appropriately rename `name` variable in file manager to `path`.
> file_mgr: appropriately rename name -> path

- src/services/spotify.js
> chore: fix spotify urification

- cli.js
- src/file_mgr.js
- test/index.js
Use async io exclusively instead of mixing the two, as it would have an impact on concurrency.
> Asyncify file io

- README.md
- cli.js
- package-lock.json
- package.json
- yarn.lock
Fixes #182.
Uses the correct cover art extension by inferring that from the image.
> fix cover art extension

- Dockerfile
> drop libstdc++

- .github/workflows/tests.yml
https://github.com/miraclx/freyr-js/runs/7977248558?check_suite_focus=true failed from lack of permissions
> pin sticky pull request comment workflow

- README.md
part of d089975d808b9d096e8703b3a3ec0b7a12b5d6b6
> update node version

- .github/workflows/tests.yml
Should help code duplication.
Slight change though, as a result of https://github.com/orgs/community/discussions/25364
Current Runs:
Previous:
Also experimented with dissociating the test type: https://github.com/miraclx/freyr-js/commit/d96921422568405139414cabca211f9c19506e02 [CI Run](https://github.com/miraclx/freyr-js/actions/runs/2975912643)
> matrixify CI

- .github/workflows/tests.yml
Experiment to see if we can have dynamic base branch labels instead of the fixed "latest master".
> ci(docker): dyn base branch

- src/async_queue.js
In the case that an AsyncQueue with provisioned resources was ever aborted, those resources would live for as long as the asyncQueue is referenced, which could cause memory to or in our case, workers to stick around without being used.
> dealloc async queue provisioned resources on abort

- src/file_mgr.js
- test/index.js
> truncate files before writing to them

- test/index.js
process.exit inhibits the `fileMgr` garbage collector from running
we need to exit the current task, ensure to manually run the fileMgr GC, and then finally exit with the specified code
> test: no abrupt process.exit

- .github/linters/.gitleaks.toml
- .github/workflows/tests.yml
- .gitleaksignore
- conf.json
Fixes https://github.com/miraclx/freyr-js/issues/91, updates Apple Music token
> chore: update apple music token

- cli.js
> fix: disable PNS for old iPod support

- conf.json
- Update Spotify credentials
- Update Apple Music credentials
Fixes #448, #451, #447, #439.
> Update service credentials

- package-lock.json
- yarn.lock
Fix audit issues in cookie-jar and http-cache-semantics
> fix dep vulnerability issues

- conf.json
- yarn.lock
Fixes #503. Updates Apple Music's credentials.
> chore(Apple Music): update credentials

- cli.js
- package-lock.json
- package.json
- yarn.lock
Disable the progress bar when we detect a tty is absent.
Fixes #384, #504.
> feat: disable bar support in the absence of a tty

- src/services/youtube.js
> fix(YouTube): fix omission in source search logic

- src/services/youtube.js
> chore(YouTube): fix duration factor in source search

- src/services/deezer.js
> fix: parse a locale in the url output from parseURI

- conf.json
Resolves https://github.com/miraclx/freyr-js/issues/452.
Updates Apple Music Token.
> chore: update developer token

- README.md
"Confiuration" was spelt wrong :>
> Update README.md Spelling mistake

- cli.js
- src/services/spotify.js
Non-explicit tracks should be tagged "Inoffensive"
Clean means explicit tracks that have been "cleaned"
> non-explicit tracks should be tagged "inoffensive"

- cli.js
```console
$ AtomicParsley "Caroline Polachek/Desire, I Want To Turn Into You/08 Blood And Butter.m4a" -t
...
Atom "sonm" contains: Blood And Butter
Atom "soal" contains: Desire, I Want To Turn Into You
Atom "soar" contains: Caroline Polachek
...
```
> feat(meta): embed sort metadata

- package-lock.json
- package.json
- yarn.lock
> chore(deps): bump `youtube-dl-exec` to v3
